"""
script_15_baselines_openai.py — Missing baselines for the GPT-4o-mini reader

WHY THIS EXISTS
  script_10_reader_scaling.py ran oracle / phase3 / phase4 under GPT-4o-mini and
  showed the F1 ceiling jumps 0.175 -> 0.455 (reader was the bottleneck). But it
  never ran the *reference* baselines under the strong reader:

      no_routing (concat top-k from the union of all sources)   <-- the decisive one
      random     (seed=42, same as script_7)
      majority   (route everything to the train-majority type)

  Without no_routing under GPT-4o-mini we cannot answer the reviewer's core
  question: *does routing actually beat "just retrieve from everything" once the
  reader can use the evidence?* Under Llama-8B it did NOT (oracle 0.1745 <
  no_routing 0.1775). This script computes those three numbers so the comparison
  is complete and the "end-to-end improvements are weak" critique can be settled.

REUSE / COST
  Reuses the existing generation cache (phase5_results/reader_scaling_openai_cache.json).
    - random & majority route to single source types already generated by
      oracle/phase3/phase4 -> almost entirely cache hits (~$0).
    - no_routing uses picked_type="all" -> ~1286 fresh generations (~$1).

USAGE
  export OPENAI_API_KEY="sk-..."          # or rely on the key baked into script_10
  python script_15_baselines_openai.py                       # full test set
  python script_15_baselines_openai.py --n 50                # smoke test
  python script_15_baselines_openai.py --methods no_routing  # just the decisive one

OUTPUT
  phase5_results/reader_scaling_openai_baselines.json   (the 3 new baseline blocks)
  Merges the same blocks into reader_scaling_openai_metrics.json
  Reprints the full GPT-4o-mini vs Llama-8B comparison table.
"""

import argparse
import json
import time
import gc
from collections import Counter, defaultdict

import numpy as np
import torch
from tqdm import tqdm

# Reuse everything from the reader-scaling script so retrieval, prompting,
# normalization and the API client are byte-identical to the oracle/phase3 runs.
from script_10_reader_scaling import (
    APIReader, GenerationCache, MultiSourceRetriever,
    load_bge, encode_queries, load_test_records, oracle_type,
    f1_score, exact_match,
    routing_random, routing_majority, routing_oracle,
    RESULTS_DIR, TEST_FILE, READER_CONFIGS, TOP_K,
)
from sourceformer import SOURCE_TYPES
from phase4_components import format_chunks, ChunkDB

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
READER_KEY = "openai"   # this script is specifically the GPT-4o-mini gap-filler


# -----------------------------------------------------------------------------
# search_all_union — identical to script_7_evaluation.MultiSourceRetriever.
# script_10's retriever only has search_type, so we add the union search here.
# -----------------------------------------------------------------------------
def search_all_union(retriever, query_embs_np, top_k):
    B = query_embs_np.shape[0]
    all_scores, all_cids = [], []
    for ds in ["nq", "triviaqa", "ott", "tat", "kg"]:
        s, fids = retriever.ds_indices[ds].search(query_embs_np, top_k)
        cid_map = retriever.ds_chunk_ids[ds]
        c = np.empty((B, top_k), dtype=object)
        for r in range(B):
            for col in range(top_k):
                c[r, col] = cid_map[fids[r, col]]
        all_scores.append(s); all_cids.append(c)
    merged_scores = np.concatenate(all_scores, axis=1)
    merged_cids = np.concatenate(all_cids, axis=1)
    top_indices = np.argsort(-merged_scores, axis=1)[:, :top_k]
    out = np.empty((B, top_k), dtype=object)
    for r in range(B):
        for c in range(top_k):
            out[r, c] = merged_cids[r, top_indices[r, c]]
    return out


# -----------------------------------------------------------------------------
# Evaluation loop. Mirrors script_10.evaluate_method but adds the no_routing
# branch (picked_type="all" via search_all_union) and does not require routing
# decisions for no_routing.
# -----------------------------------------------------------------------------
def evaluate(method_name, records, query_embs, routing_decisions,
             retriever, chunk_db, reader, cache, eval_n=None):
    n = len(records) if eval_n is None else min(eval_n, len(records))
    print(f"\n=== {method_name} | reader={reader.name} | N={n} ===")

    f1s, ems, recall_at_picked = [], [], []
    per_type_f1 = defaultdict(list)
    predictions = []
    n_cached = 0
    t0 = time.time()

    for i in tqdm(range(n), desc=method_name):
        r = records[i]
        q_emb = query_embs[i:i + 1]

        if method_name == "no_routing":
            cids = search_all_union(retriever, q_emb, TOP_K)[0]
            picked_type = "all"
        else:
            picked_idx = int(routing_decisions[i])
            picked_type = SOURCE_TYPES[picked_idx]
            cids = retriever.search_type(q_emb, picked_type, TOP_K)[0]

        chunks_dict = chunk_db.get_many(list(cids))
        chunks = [chunks_dict[c] for c in cids]
        context = format_chunks(chunks)

        cached = cache.get(i, picked_type)
        if cached is not None:
            pred = cached["answer"]
            n_cached += 1
        else:
            pred = reader.generate(r["query"], context)
            cache.put(i, picked_type, pred)

        f1 = f1_score(pred, r["answer"])
        em = exact_match(pred, r["answer"])
        oracle_t = SOURCE_TYPES[r["oracle_label"]]
        per_type_f1[oracle_t].append(f1)

        relevant = set(cid for cid, s in r["relevant_chunks"].items() if s > 0)
        recall_at_picked.append(float(bool(set(cids.tolist()) & relevant)))
        f1s.append(f1); ems.append(em)
        predictions.append({
            "id": r["id"], "query": r["query"], "gold": r["answer"],
            "predicted": pred, "picked_type": picked_type,
            "oracle_type": oracle_t, "f1": f1, "em": em,
        })

        if (i + 1) % 50 == 0:
            cache.save()
            eta = (time.time() - t0) / (i + 1) * (n - i - 1)
            print(f"    [{i+1}/{n}] F1={np.mean(f1s):.4f} cached={n_cached} "
                  f"cost=${reader.estimated_cost():.3f} ETA={eta/60:.1f}min")

    cache.save()
    metrics = {
        "method": method_name,
        "reader": reader.name,
        "n": n,
        "f1_mean": float(np.mean(f1s)),
        "em_mean": float(np.mean(ems)),
        "recall_at_picked": float(np.mean(recall_at_picked)),
        "per_type_f1": {k: float(np.mean(v)) for k, v in per_type_f1.items()},
        "per_type_n": {k: len(v) for k, v in per_type_f1.items()},
    }

    # Routing accuracy (undefined for no_routing — it doesn't pick a type)
    if method_name != "no_routing":
        oracle = np.array([r["oracle_label"] for r in records[:n]])
        dec = np.asarray(routing_decisions[:n])
        per_type_acc = {}
        for j, t in enumerate(SOURCE_TYPES):
            mask = (oracle == j)
            if mask.sum() > 0:
                per_type_acc[t] = float((dec[mask] == oracle[mask]).mean())
        metrics["routing_acc"] = float((dec == oracle).mean())
        metrics["routing_macro"] = float(np.mean(list(per_type_acc.values())))
        metrics["routing_per_type_acc"] = per_type_acc

    out_path = RESULTS_DIR / f"reader_scaling_{READER_KEY}_predictions_{method_name}.jsonl"
    with open(out_path, "w") as f:
        for p in predictions:
            f.write(json.dumps(p) + "\n")

    print(f"  F1={metrics['f1_mean']:.4f}  EM={metrics['em_mean']:.4f}  "
          f"R@picked={metrics['recall_at_picked']:.4f}  (cached {n_cached}/{n})")
    return metrics


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=None, help="limit to first N queries")
    ap.add_argument("--methods", nargs="+",
                    default=["random", "majority", "no_routing"],
                    choices=["random", "majority", "no_routing"])
    args = ap.parse_args()

    cache_path = RESULTS_DIR / f"reader_scaling_{READER_KEY}_cache.json"
    print("=" * 70)
    print("Missing GPT-4o-mini baselines (random / majority / no_routing)")
    print("=" * 70)
    print(f"  Reader: {READER_CONFIGS[READER_KEY]['name']}")
    print(f"  Cache:  {cache_path}")

    reader = APIReader(READER_KEY)
    cache = GenerationCache(cache_path)

    print("\nLoading test set...")
    test_records = load_test_records(TEST_FILE)

    print("Loading train set (for majority label)...")
    with open("mmrag_train.json") as f:
        train_data = json.load(f)
    train_records = [{"oracle_label": oracle_type(it)} for it in train_data
                     if oracle_type(it) is not None]

    print("\nLoading FAISS indices + chunk DB...")
    chunk_db = ChunkDB("chunk_texts.db")
    retriever = MultiSourceRetriever()

    print("\nEncoding test queries...")
    bge, bge_tok = load_bge()
    query_embs = encode_queries(bge, bge_tok, [r["query"] for r in test_records])
    del bge, bge_tok
    gc.collect(); torch.cuda.empty_cache()

    new_metrics = {}
    if "random" in args.methods:
        new_metrics["random"] = evaluate(
            "random", test_records, query_embs,
            routing_random(test_records, seed=42),
            retriever, chunk_db, reader, cache, args.n)
    if "majority" in args.methods:
        new_metrics["majority"] = evaluate(
            "majority", test_records, query_embs,
            routing_majority(test_records, train_records),
            retriever, chunk_db, reader, cache, args.n)
    if "no_routing" in args.methods:
        new_metrics["no_routing"] = evaluate(
            "no_routing", test_records, query_embs, None,
            retriever, chunk_db, reader, cache, args.n)

    # Save the new baselines on their own...
    with open(RESULTS_DIR / f"reader_scaling_{READER_KEY}_baselines.json", "w") as f:
        json.dump(new_metrics, f, indent=2)

    # ...and merge into the main GPT-4o-mini metrics file next to oracle/phase3/phase4.
    main_path = RESULTS_DIR / f"reader_scaling_{READER_KEY}_metrics.json"
    merged = {}
    if main_path.exists():
        with open(main_path) as f:
            merged = json.load(f)
    merged.update(new_metrics)
    merged["api_cost_baselines"] = {
        "total_usd": reader.estimated_cost(),
        "input_tokens": reader.total_input_tokens,
        "output_tokens": reader.total_output_tokens,
    }
    with open(main_path, "w") as f:
        json.dump(merged, f, indent=2)

    # ---- The decisive table: routing vs no_routing under each reader ----------
    llama = {}
    p5 = RESULTS_DIR / "phase5_metrics.json"
    if p5.exists():
        with open(p5) as f:
            llama = json.load(f)

    def f1(d, k):
        v = d.get(k, {})
        return v.get("f1_mean", float("nan"))

    print("\n" + "=" * 74)
    print("DECISIVE COMPARISON — does routing beat no_routing?")
    print("=" * 74)
    print(f"{'method':<14}{'Llama-3.1-8B-4bit':>22}{'GPT-4o-mini':>18}")
    print("-" * 74)
    for k in ["random", "majority", "no_routing", "oracle", "phase3", "phase4"]:
        print(f"{k:<14}{f1(llama, k):>22.4f}{f1(merged, k):>18.4f}")
    print("-" * 74)
    gap = f1(merged, "phase3") - f1(merged, "no_routing")
    print(f"GPT-4o-mini  phase3 - no_routing = {gap:+.4f}  "
          f"({'routing WINS' if gap > 0 else 'no_routing wins -> pivot to efficiency angle'})")
    print(f"\nBaseline API cost this run: ${reader.estimated_cost():.3f}")
    print(f"Saved -> {main_path}")


if __name__ == "__main__":
    main()
