"""
script_28_recall_r3ag_llm.py  —  Exact recall@picked for R³AG-RQ, R³AG-full
                                 and the zero-shot GPT-4o-mini classifier

PURPOSE
  Table 4 reports recall@picked for every routing method except R³AG-RQ,
  R³AG-full and GPT-4o-mini (zero-shot). Reviewer 2 objected that the metric
  the paper argues is the appropriate retrieval-side measure was therefore not
  available for the competing methods. This script fills all three cells. Two
  come from predictions already saved when those methods were run; the third
  (R³AG-RQ) comes from a rerun, described below. No API calls are involved:

    R³AG-full            phase6_results/r3ag_test_preds_seed{42,123,2026}.npy
    GPT-4o-mini (0-shot) phase5_results/llm_classifier_k3_results.json["records"]
    R³AG-RQ              phase6_results/r3ag_test_preds_rq_seed{42,123,2026}.npy

  R³AG-RQ's predictions were not originally retained. They are regenerated by

      python script_13_r3ag.py --skip_phase0 --tag _rq --seeds 42 123 2026

  --skip_phase0 substitutes the retrieval-quality label for the generation
  utility label in both InfoNCE heads and in the Stage-2 fusion target, which
  is exactly the "retrieval-quality labels only, no generation signal"
  configuration the paper describes for R³AG-RQ. The rerun reproduces the
  published macro (0.663 ± 0.003) and per-type accuracies (0.825 / 0.754 /
  0.411) to three decimals, which is what licenses using it here. --tag keeps
  the variant's artifacts from overwriting the R³AG-full ones.

METHOD
  The retrieval and hit definition are copied verbatim from
  script_24_exact_recall_faiss.py so the new numbers are computed by an
  identical code path to the published ones (same TOP_K=10, same per-dataset
  union within a source type, same "score > 0" relevance rule, same cached
  query embeddings). Any change here must be mirrored there.

  recall@picked does not depend on the gold routing label at all -- it is a
  function of the chosen source, the retrieved chunks and the relevance
  annotations only. The gold label is used here purely as an alignment guard:
  each method's routing macro is recomputed from its saved predictions and
  must reproduce the value already reported for it, or the script refuses to
  write anything.

  That guard exposed a genuine inconsistency, so this script pins both
  conventions down explicitly:

    SUM convention  argmax over summed per-source dataset_score
                    (nq+triviaqa, ott+tat, kg) -> 717/359/210 text/table/kg.
                    This is the paper's canonical routing label: it is what
                    script_13_r3ag.py scores against, and its class counts are
                    the n column of Table 8.

    ID convention   gold taken from the query id prefix, i.e. which dataset
                    the question originated in, with a fallback to SUM.
                    -> 680/398/208. Used only by
                    script_27_llm_classifier_baseline.py.

  The two disagree on 51 of 1286 queries. The zero-shot GPT-4o-mini macro
  reported in Table 4 (0.545) is an ID-convention number, so as published it
  is not scored against the same labels as every other row of that table.
  Under the canonical SUM convention the same predictions give 0.542. This
  script reports both and writes both.

NO GPU needed. Pure FAISS + numpy. Runtime: ~10 minutes (4 method-seeds).

USAGE
  conda activate chestx && python script_28_recall_r3ag_llm.py

OUTPUT
  phase5_results/exact_recall_at_picked_faiss.json   (merged, existing keys kept)
"""

# ==========================================================================
# SUPERSEDED -- DO NOT USE FOR recall@picked
#
# retrieve_chunk_ids() below unions the top-10 of EACH constituent index,
# so a source type spanning two indices (text = nq+triviaqa, table =
# ott+tat) returns up to 20 chunks while kg returns 10. That contradicts
# the paper's definition of recall@picked ("top-10 chunks from the routed
# source") and the reader's actual 10-chunk context, and it inflates the
# metric asymmetrically in favour of KG-averse routers (+0.02 to +0.04 for
# text/table-heavy methods, ~0 for KG-collapsed ones).
#
# The canonical values come from script_32_recall_canonical.py, which calls
# script_7_evaluation.MultiSourceRetriever.search_type() -- merge the
# constituent indices by score, keep the global top-10. See
# script_31_recall_convention_audit.py for the side-by-side evidence.
# ==========================================================================


import json
import sys
import numpy as np
from pathlib import Path
from collections import defaultdict
import faiss

RESULTS_DIR  = Path("phase5_results")
PHASE6_DIR   = Path("phase6_results")
TEST_FILE    = "mmrag_test.json"
SOURCE_TYPES = ["text", "table", "kg"]
SOURCE_IDX   = {s: i for i, s in enumerate(SOURCE_TYPES)}
TOP_K        = 10
SEEDS        = [42, 123, 2026]

# Values these recomputations must reproduce. Read from the originating
# artifact rather than hardcoded, so the guard cannot be defeated by a
# transcription slip, and each is checked under the label convention the
# script that produced it actually used (see module docstring).
EXPECTED_MACRO_SOURCES = {
    "r3ag_full":      (PHASE6_DIR / "r3ag_summary.json",           "mean_macro", "sum"),
    "r3ag_rq":        (PHASE6_DIR / "r3ag_summary_rq.json",        "mean_macro", "sum"),
    "gpt4o_zeroshot": (RESULTS_DIR / "llm_classifier_k3_results.json", "macro_acc", "id"),
}
MACRO_TOL = 1e-9

SOURCE_TO_DATASETS = {
    "text":  ["nq", "triviaqa"],
    "table": ["ott", "tat"],
    "kg":    ["kg"],
}

# ── load test data ────────────────────────────────────────────────────────────
print("Loading test data...")
with open(TEST_FILE) as f:
    test_data = json.load(f)
n = len(test_data)
print(f"  {n} test queries")

relevant_chunks = []
for item in test_data:
    rel = {cid for cid, score in item.get("relevant_chunks", {}).items() if score > 0}
    relevant_chunks.append(rel)


def gold_sum(item):
    """Canonical routing label: argmax over SUMMED per-source dataset_score.

    Identical to hard_label_k3() in script_13_r3ag.py. Class counts under this
    rule are 717 text / 359 table / 210 kg, matching the n column of Table 8.
    """
    s = item["dataset_score"]
    return int(np.argmax([
        s.get("nq", 0) + s.get("triviaqa", 0),
        s.get("ott", 0) + s.get("tat", 0),
        s.get("kg", 0),
    ]))


def gold_id(item):
    """Provenance label: which dataset the query came from, SUM as fallback.

    Identical to gold_label_k3() in script_27_llm_classifier_baseline.py.
    Retained only to reproduce that script's published macro.
    """
    rid = str(item.get("id", "")).lower()
    if rid.startswith(("m.", "kg_")):
        return SOURCE_IDX["kg"]
    if rid.startswith(("nq_", "triviaqa_")):
        return SOURCE_IDX["text"]
    if rid.startswith(("ott_", "tat_")):
        return SOURCE_IDX["table"]
    return gold_sum(item)


GOLD = {
    "sum": np.array([gold_sum(it) for it in test_data]),
    "id":  np.array([gold_id(it) for it in test_data]),
}
print(f"  gold conventions disagree on "
      f"{int((GOLD['sum'] != GOLD['id']).sum())} / {n} queries")


def macro_accuracy(decisions, convention="sum"):
    """Per-source-type accuracy averaged equally over types present in gold."""
    gold = GOLD[convention]
    per_type = []
    for k in range(len(SOURCE_TYPES)):
        mask = gold == k
        if mask.sum() == 0:
            continue
        per_type.append(float((decisions[mask] == k).mean()))
    return float(np.mean(per_type))


# ── load FAISS indices ────────────────────────────────────────────────────────
print("Loading FAISS indices...")
faiss_indices = {}
chunk_id_lists = {}
FAISS_DIR = Path("faiss_indices")

for src, datasets in SOURCE_TO_DATASETS.items():
    faiss_indices[src] = {}
    chunk_id_lists[src] = {}
    for ds in datasets:
        idx_path = FAISS_DIR / ds / "index.faiss"
        id_file = FAISS_DIR / ds / "chunk_ids.npy"
        if not idx_path.exists() or not id_file.exists():
            sys.exit(f"  FATAL: missing index or chunk_ids for {ds}")
        index = faiss.read_index(str(idx_path))
        ids = list(np.load(id_file, allow_pickle=True))
        faiss_indices[src][ds] = index
        chunk_id_lists[src][ds] = ids
        print(f"  {ds}: {index.ntotal} vectors, {len(ids)} chunk IDs")

# ── load query embeddings ─────────────────────────────────────────────────────
print("Loading query embeddings...")
test_cache = Path("query_emb_cache/test_embs_k3.npy")
if not test_cache.exists():
    test_cache = Path("query_emb_cache/test_embs.npy")
test_embs = np.load(test_cache).astype(np.float32)
print(f"  shape: {test_embs.shape}")
assert test_embs.shape[0] == n, "query embedding count != test set size"


# ── retrieval + recall (identical to script_24_exact_recall_faiss.py) ─────────
def retrieve_chunk_ids(query_emb, source):
    """Return set of top-K chunk IDs from the given source."""
    retrieved = set()
    q = query_emb.reshape(1, -1)
    for ds, index in faiss_indices[source].items():
        if index.ntotal == 0:
            continue
        k = min(TOP_K, index.ntotal)
        _, positions = index.search(q, k)
        ids = chunk_id_lists[source][ds]
        for pos in positions[0]:
            if 0 <= pos < len(ids):
                retrieved.add(ids[pos])
    return retrieved


def compute_recall(decisions, name="method"):
    """decisions: (n,) int array of source indices."""
    hits = 0
    for i in range(n):
        src = SOURCE_TYPES[decisions[i]]
        retrieved = retrieve_chunk_ids(test_embs[i], src)
        if retrieved & relevant_chunks[i]:
            hits += 1
        if (i + 1) % 200 == 0:
            print(f"  [{name}] {i+1}/{n}  running recall={hits/(i+1):.4f}")
    recall = hits / n
    print(f"  [{name}] recall@picked = {recall:.4f}")
    return recall


# ── gather routing decisions ──────────────────────────────────────────────────
print("\nLoading routing decisions...")
decisions = {}

# R³AG variants: one prediction array per seed each
def load_r3ag(tag, label):
    out = {}
    for seed in SEEDS:
        p = PHASE6_DIR / f"r3ag_test_preds{tag}_seed{seed}.npy"
        if not p.exists():
            sys.exit(f"  FATAL: {p} not found"
                     + ("  (run script_13_r3ag.py --skip_phase0 --tag _rq)"
                        if tag else ""))
        dec = np.load(p, allow_pickle=True).astype(int)
        assert dec.shape == (n,), f"{p}: expected ({n},), got {dec.shape}"
        out[seed] = dec
    print(f"  {label}: {len(out)} seeds loaded")
    return out

r3ag_seed_decs = load_r3ag("", "R³AG-full")
r3ag_rq_seed_decs = load_r3ag("_rq", "R³AG-RQ")

# Zero-shot GPT-4o-mini: per-query source-type strings, in test-set order
llm_path = RESULTS_DIR / "llm_classifier_k3_results.json"
if not llm_path.exists():
    sys.exit(f"  FATAL: {llm_path} not found")
llm = json.load(open(llm_path))
records = llm["records"]
assert len(records) == n, f"llm records {len(records)} != {n}"
# order check against the test file before trusting positional alignment
mismatch = sum(
    1 for i in range(n)
    if records[i]["question"].strip() != test_data[i]["query"].strip()
)
if mismatch:
    sys.exit(f"  FATAL: {mismatch} llm records out of test-set order")
unknown = {r["pred"] for r in records} - set(SOURCE_TYPES)
if unknown:
    sys.exit(f"  FATAL: unparseable llm predictions: {unknown}")
decisions["gpt4o_zeroshot"] = np.array([SOURCE_IDX[r["pred"]] for r in records])
print(f"  GPT-4o-mini (zero-shot): {n} predictions loaded, order verified")

# ── alignment guard: recompute macro and compare to the reported value ────────
print("\nVerifying prediction alignment via routing macro accuracy...")
recomputed = {
    "r3ag_full": {
        c: float(np.mean([macro_accuracy(d, c) for d in r3ag_seed_decs.values()]))
        for c in ("sum", "id")
    },
    "r3ag_rq": {
        c: float(np.mean([macro_accuracy(d, c) for d in r3ag_rq_seed_decs.values()]))
        for c in ("sum", "id")
    },
    "gpt4o_zeroshot": {
        c: macro_accuracy(decisions["gpt4o_zeroshot"], c) for c in ("sum", "id")
    },
}
EXPECTED_MACRO = {}
for _name, (_path, _key, _conv) in EXPECTED_MACRO_SOURCES.items():
    if not _path.exists():
        sys.exit(f"  FATAL: {_path} not found (cannot verify {_name})")
    EXPECTED_MACRO[_name] = (float(json.load(open(_path))[_key]), _conv)

ok = True
for name, (exp, conv) in EXPECTED_MACRO.items():
    got = recomputed[name][conv]
    good = abs(got - exp) < MACRO_TOL
    ok &= good
    print(f"  {name:<18} [{conv}-convention] recomputed {got:.6f}  "
          f"reported {exp:.6f}  {'OK' if good else 'MISMATCH'}")
    other = "id" if conv == "sum" else "sum"
    print(f"  {'':<18} [{other}-convention] {recomputed[name][other]:.6f}")
if not ok:
    sys.exit("\nFATAL: macro mismatch -- predictions are not aligned with the "
             "test set as loaded here. Refusing to write results.")

# ── compute recall@picked ─────────────────────────────────────────────────────
print("\nComputing exact recall@picked...")
results = {}

for key, decs, label in (("r3ag_full", r3ag_seed_decs, "R3AG-full"),
                         ("r3ag_rq", r3ag_rq_seed_decs, "R3AG-RQ")):
    rec = []
    for seed in SEEDS:
        print(f"  {label} seed {seed}...")
        rec.append(compute_recall(decs[seed], f"{label}-s{seed}"))
    results[key] = {
        "recall_at_picked": float(np.mean(rec)),
        "recall_at_picked_std": float(np.std(rec, ddof=1)),
        "per_seed": rec,
        "macro_sum_convention": recomputed[key]["sum"],
        "macro_id_convention": recomputed[key]["id"],
        "macro_as_published": recomputed[key]["sum"],
        "source": "exact (FAISS)",
    }

print("  GPT-4o-mini (zero-shot)...")
results["gpt4o_zeroshot"] = {
    "recall_at_picked": compute_recall(decisions["gpt4o_zeroshot"], "GPT4o-0shot"),
    "macro_sum_convention": recomputed["gpt4o_zeroshot"]["sum"],
    "macro_id_convention": recomputed["gpt4o_zeroshot"]["id"],
    "macro_as_published": recomputed["gpt4o_zeroshot"]["id"],
    "note": ("Table 4 publishes the id-convention macro; the sum-convention "
             "value is the one comparable with every other row."),
    "n_seeds": 1,
    "source": "exact (FAISS)",
}

# ── merge into the existing file, preserving published values ─────────────────
out = RESULTS_DIR / "exact_recall_at_picked_faiss.json"
existing = json.load(open(out)) if out.exists() else {}
stale = (set(existing) & set(results)) - {"r3ag_full", "r3ag_rq", "gpt4o_zeroshot"}
if stale:
    sys.exit(f"FATAL: would overwrite unrelated keys {stale}; aborting.")
existing.update(results)
with open(out, "w") as f:
    json.dump(existing, f, indent=2)

print("\n" + "=" * 62)
print("NEW EXACT RECALL@PICKED VALUES")
print("=" * 62)
for m, v in results.items():
    line = f"  {m:<20} {v['recall_at_picked']:.4f}"
    if "recall_at_picked_std" in v:
        line += f" ± {v['recall_at_picked_std']:.4f} (n={len(v['per_seed'])} seeds)"
    print(line)
print(f"\nMerged → {out}")
print("All three previously-blank Table 4 recall@picked cells are now filled.")
